
project_id = "sgklvuzgrkcnvarvhfog"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
only_local = true
smtp_port = 54326
pop3_port = 54327

[functions.send-contact-notification]
verify_jwt = false

[auth]
enabled = true
port = 54326
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true
security_captcha_enabled = false
security_captcha_provider = "hcaptcha"
security_captcha_secret = "env(CAPTCHA_SECRET)"
security_update_password_captcha_enabled = false
security_manual_linking_enabled = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_password_change = false
enable_reauthentication = false

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }}"
max_frequency = 60

[auth.external.apple]
enabled = false
client_id = ""
secret = "env(AUTH_APPLE_SECRET)"
redirect_uri = ""

[auth.external.azure]
enabled = false
client_id = ""
secret = "env(AUTH_AZURE_SECRET)"
url = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = "env(AUTH_BITBUCKET_SECRET)"

[auth.external.discord]
enabled = false
client_id = ""
secret = "env(AUTH_DISCORD_SECRET)"

[auth.external.facebook]
enabled = false
client_id = ""
secret = "env(AUTH_FACEBOOK_SECRET)"

[auth.external.figma]
enabled = false
client_id = ""
secret = "env(AUTH_FIGMA_SECRET)"

[auth.external.github]
enabled = false
client_id = ""
secret = "env(AUTH_GITHUB_SECRET)"

[auth.external.gitlab]
enabled = false
client_id = ""
secret = "env(AUTH_GITLAB_SECRET)"

[auth.external.google]
enabled = false
client_id = ""
secret = "env(AUTH_GOOGLE_SECRET)"
skip_nonce_check = false

[auth.external.keycloak]
enabled = false
client_id = ""
secret = "env(AUTH_KEYCLOAK_SECRET)"
url = ""

[auth.external.linkedin]
enabled = false
client_id = ""
secret = "env(AUTH_LINKEDIN_SECRET)"

[auth.external.notion]
enabled = false
client_id = ""
secret = "env(AUTH_NOTION_SECRET)"

[auth.external.twitch]
enabled = false
client_id = ""
secret = "env(AUTH_TWITCH_SECRET)"

[auth.external.twitter]
enabled = false
client_id = ""
secret = "env(AUTH_TWITTER_SECRET)"

[auth.external.slack]
enabled = false
client_id = ""
secret = "env(AUTH_SLACK_SECRET)"

[auth.external.spotify]
enabled = false
client_id = ""
secret = "env(AUTH_SPOTIFY_SECRET)"

[auth.external.workos]
enabled = false
client_id = ""
secret = "env(AUTH_WORKOS_SECRET)"

[auth.external.zoom]
enabled = false
client_id = ""
secret = "env(AUTH_ZOOM_SECRET)"

[edge-runtime]
enabled = true
policy = "per_worker"
inspector_port = 8083
