// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgklvuzgrkcnvarvhfog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNna2x2dXpncmtjbnZhcnZoZm9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDQ3NzIsImV4cCI6MjA2NDUyMDc3Mn0.GKAjz7YzrWV9i1JcthiDVEa26pyo_ClyAVNTdnJon3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);